name: output issues
on: push 
jobs:
    output_issues:
            runs-on: ubuntu-latest
            steps:
                - name: output github issues
                  run: |
                    echo ${{ toJSON(github.event) }}
                - name: Cleanup
                  if: always()
                  run: |
                    echo "::notice::Running cleanup"